### ISSUE TITLE
Поменять очередность обновления таблиц в ms

### ISSUE THREAD

**Issue by Stockuper** [Stockuper/NLS#1]
@pepelazz 
В данном блоке обновлений первую и вторую таблицу нужно запускать одновременно. Следующие три последовательно, после обновления первых двух

select * from mutual_settlement_sync_deferral_reference('{"is_clear": true}');

select * from mutual_settlement_sync_detailed_settlements('{"days": 10000}');

select * from mutual_settlement_sync_overdue_arrears('{"days": 10000}');

select * from mutual_settlement_sync_customer_settlement('{"days": 10000}');

select * from mutual_settlement_sync_main_report('{"is_clear": true}');

**Comment by pepelazz** [comment]
done

**Comment by Stockuper** [comment]
будем считать, что работает
